Resources:
  webserver:
    Type: AWS::EC2::Instance
    Metadata:
      AWS::CLoudFormation::Init:
        config:
          packages:
            yum:
              httpd: []

          services:
            sysvinit:
              httpd:
                enabled: true
                ensureRunning: true

    Properties:
      ImageId: ami-b46f48db
      InstanceType: m8.large
      SecurityGroups:
        - !Ref securityGroup
      UserData:
        Fn::Base64:
          !Sub |
            #!/bin/bash -xe
            yum install -y aws-cfn-bootstrap
            /opt/bin/aws/cfn-init -s ${AWS::StackId} -r webserver --region ${AWS::Region} -v

  securityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: access web application
      SecurityGroupIngress:
        -
          IpProtocol: tcp
          CidrIp: 0.0.0.0/0
          FromPort: 80
          ToPort: 80

Outputs:
  webserverIPAddress:
    Value: !Sub ${webserver.PublicIp}
